# compose.yaml
services:
  api:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN:-http://localhost:8080}
      APP_DB_PATH: ${APP_DB_PATH:-/app/data/fraud.db}
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - api
    restart: unless-stopped
